language: csharp
mono:
  - latest
install:
  - python3 -m venv /home/travis/pyenv
  - source /home/travis/pyenv/bin/activate
  - pip3 install numpy==1.11.1
  - pip3 install scipy==0.17.1
  - pip3 install scikit-learn==0.19.0