language: csharp
mono:
  - latest
install:
  - sudo apt-get update
  - sudo apt-get install python-pip3
  - pip3 install numpy==1.11.1
  - pip3 install scipy==0.17.1
  - pip3 install scikit-learn==0.19.0
  - python3.6