language: csharp
mono:
  - latest
python:
  -"3.4"
install:
  - sudo apt-get update
  - sudo apt-get install python-virtualenv 
  - virtualenv -p python3.4 /home/travis/pyenv
  - source /home/travis/pyenv/bin/activate
  - pip3 install numpy==1.11.1
  - pip3 install scipy==0.17.1
  - pip3 install scikit-learn==0.19.0
  - python3.4